### PR TITLE
Third homework - Katarzyna Kanska

### PR DESCRIPTION
**Pull request by kkanska**

### CODE REVIEW

**Comment by pbiecek** [comment]
Accepted, however note that your opening statement it is not:
''The only assumption of the linear model is that the following relation is satisfied: \( y = \alpha*x + \varepsilon \), where \( \varepsilon \) is a normally distributed random variable, \( \alpha \) is a constant.''.

epsilons have to be independent and with homogenous variance.

**Comment by kkanska** [comment]
I thought of n-dimentional vectors. By "epsilon is normally distributed" I
meant that it is a vector from n-dimentional normal distribution, which is
by definition a vector with independent coordinates, normally distributed
with the same mean and variance. (Still the assumption that mean is equal
to zero is missing.)
Anyway, I should have stated that more clearly.

**Comment by pbiecek** [comment]
The n-dimentional normal distribution by definition has a co-variance matrix Sigma, and there is no assumption that elements in vector are independent nor with equal variance. 
It's true only if Sigma = \sigma * I

**Comment by kkanska** [comment]
That's true... I got confused. Thank you for putting me right on that
matter and sorry for arguing.

**Pull request merged**
